# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OfUWvrf1xtALG_wV5p96y0iahiNuUAda
"""

#1
length=int(input("enter the value"))
width=int(input("enter the value"))
print(length*width)

#2
weight=80
height=1.5
bmi=(weight/height**2)
print(bmi)

#3
d={}
no_of_students=int(input("enter the number of students"))
for i in range(no_of_students):
 student=str(input("enter the student name"))
 scores=int(input("enter the score"))
 d[student]=scores
 print(d)

#4
age=int(input("enter your age"))

if age < 18:
 print("minor")
elif age >= 18 and age == 60:
 print("adult")
else:
 print("senior")

#5
str evenum
for i in range(1,51):
  if evennum = (i/2==0):
  print(evennum)

#6
entries=int(input("enter tries"))
for i in range(entries):
 while True:
  password=str(input("enter the password"))
  if password == correct:

   break
   print("password is correct")

#7
def average1(n):
    if len(n) == 0:
        return 0
    total = sum(n)
    return total / len(n)

n = [1,2,3,4,5,6,7,8,9]
avg = average1(n)
print("Average:",avg)

#8
def count_v(string):
    vowels = "hellotherebuddy"
    count = 0
    for char in string:
        if char in vowels:
            count += 1
    return count

input_str = "ThereIsAnAppleInthetree"
print("Number of vowels are:", count_v(input_str))

#9
current_dt= datetime()
print(datetime(current_dt))

from re import A
#10
try:
  a=1
  b="A"
  print(a+b)
except:
    print("non-numeric values not allowed")

#11
try:
  value=int(input("enter value"))
except ValueError:
  print("invalid value")

#12
try:
  a=50
  b=0
  print(a/b)
except ZeroDivisionError as e:
  print("0 in denominator is not allowed",e)





#13
myfile=open('/content/IA.txt','w')
print(myfile.write("Hello,Python!"))
myfile.close()

#14
myfile=open('/content/IA.txt','r')
print(myfile.read())
myfile.close()

#15
myfile=open('/content/IA.txt','a')
print(myfile.write("hey world"))
myfile.close()